name: gt_mobile_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.10.0 <=5.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  gt_mobile_foundation:
      git:
        url: https://github.com/gofinancials/gt_mobile_foundation.git
        ref: v0.0.3
  lottie: ^3.0.0
  provider: ^6.0.3
  shimmer: ^3.0.0
  styled_text:
    git:
      url: https://github.com/dirisujesse/styled_text_package.git
      path: styled_text
      ref: master
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.0.0
  vector_graphics_compiler: ^1.1.19

flutter:
  uses-material-design: true

  assets:
    - assets/images/raster/
    - assets/images/vector/
    - assets/images/vector/icons/
    - path: assets/images/vector/icons/
      transformers:
        - package: vector_graphics_compiler
  fonts:
    - family: Readex
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
    - family: Youth
      fonts:
        - asset: assets/fonts/Youth-Bold.otf
          weight: 700
        - asset: assets/fonts/Youth-Medium.otf