name: gallery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <=5.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  gt_mobile_ui:
    path: ../
  widgetbook_annotation: ^3.11.0
  widgetbook: ^3.22.0
  gt_mobile_foundation:
      git:
        url: https://github.com/gofinancials/gt_mobile_foundation.git
        ref: v0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  widgetbook_generator: ^3.22.0
  vector_graphics_compiler: ^1.1.19

flutter:
  uses-material-design: true
