name: Deploy Widgetbook to GitHub Pages

on:
  push:
    branches:
      - main # Change to your default branch (e.g., master)
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for publishing to gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          version: '3.41.6' # Specify the Flutter version you want to use
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Widgetbook
        run: flutter build web --target gallery/lib/main.dart -t widgetbook --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # The folder where flutter builds the web files
          branch: gh-pages # The branch the action should deploy to
          clean: true
